version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - login-net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sportutm
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - login-net

networks:
  login-net: